CREATE TABLE ACQUISITION_MASTER (

	ACQ_ID SERIAL NOT NULL, 
	ACQ_CODE VARCHAR(32) NULL, 
	COUNTRY INTEGER NULL, 
	IS_NEED_PRICE INTEGER NULL, 
	MSG_LOCAL VARCHAR(255) NULL, 
	MSG_PRICE_ENTRY TEXT NULL, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (ACQ_ID) 
);


CREATE TABLE ACTION_BILL (

	ACTION_BILL_ID SERIAL NOT NULL, 
	ACTION_CODE VARCHAR(32) NULL, 
	CONTRACT_CODE VARCHAR(32) NULL, 
	DISCOUNT_BY_CONTRACT DOUBLE PRECISION NULL, 
	FEE_DIAGNOSIS DOUBLE PRECISION NULL, 
	FEE_HOTEL DOUBLE PRECISION NULL, 
	FEE_OTHER DOUBLE PRECISION NULL, 
	FEE_PARTS DOUBLE PRECISION NULL, 
	FEE_SHIPPING DOUBLE PRECISION NULL, 
	FEE_TECHNICAL DOUBLE PRECISION NULL, 
	FEE_VISIT DOUBLE PRECISION NULL, 
	PAY_DATE DATE NULL, 
	P_CCY INTEGER NULL, 
	TAX DOUBLE PRECISION NULL, 
	TOTAL DOUBLE PRECISION NULL, 
	TOTAL_PAY DOUBLE PRECISION NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (ACTION_BILL_ID) 
);


CREATE TABLE ACTION_LOG (

	ACTION_ID SERIAL NOT NULL, 
	ACTION_CODE VARCHAR(32) NULL, 
	ACTION_DATE DATE NULL, 
	ACTION_START_CONFIRM_IMG BYTEA NULL, 
	ACTION_TYPE VARCHAR(32) NULL, 
	CHECK_START_CONFIRM_IMG BYTEA NULL, 
	CLIENT_SIDE_MGMT_CODE TEXT NULL, 
	COMPLAINT TEXT NULL, 
	CONTACT_DATE DATE NULL, 
	CONTACT_PSN VARCHAR(32) NULL, 
	DELIVERY_METHOD TEXT NULL, 
	DEV_CODE VARCHAR(32) NULL, 
	FINISH_DATE DATE NULL, 
	HOSP_CODE VARCHAR(32) NULL, 
	HOSP_CONTACT_PSN VARCHAR(32) NULL, 
	HOSP_DEPT_CODE VARCHAR(32) NULL, 
	INSTALL_CONFIRM_IMG BYTEA NULL, 
	OCCUR_DATE DATE NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (ACTION_ID) 
);


CREATE TABLE ACTION_TYPE_MASTER (

	ACTION_TYPE_ID SERIAL NOT NULL, 
	ACTION_TYPE_CODE VARCHAR(32) NULL, 
	COUNTRY INTEGER NULL, 
	LABEL VARCHAR(255) NULL, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (ACTION_TYPE_ID) 
);


CREATE TABLE ADDRESS (

	ADDR_ID SERIAL NOT NULL, 
	ADDRESS1 VARCHAR(255) NULL, 
	ADDRESS2 VARCHAR(255) NULL, 
	ADDR_CODE VARCHAR(32) NULL, 
	CITY VARCHAR(255) NULL, 
	CONTACT_METHOD TEXT NULL, 
	COUNTRY INTEGER NULL, 
	PROVINCE VARCHAR(255) NULL, 
	ZIP_CODE VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (ADDR_ID) 
);


CREATE TABLE ALERT_BY_COUNT (

	COUNTER_BASE_ID SERIAL NOT NULL, 
	CKLIST_CODE VARCHAR(32) NULL, 
	COUNTER_BASE_CODE VARCHAR(32) NULL, 
	DESCRIPTION TEXT NULL, 
	INTERVAL_COUNT INTEGER NULL, 
	LIMIT_COUNT INTEGER NULL, 
	MDEV_CODE VARCHAR(32) NULL, 
	NAME VARCHAR(255) NULL, 
	UNIT VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (COUNTER_BASE_ID) 
);


CREATE TABLE APPROVAL_CONFIG (

	CONFIG_ID SERIAL NOT NULL, 
	DATA_TYPE VARCHAR(32) NOT NULL, 
	DISABLE_APPROVE INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (CONFIG_ID) 
);


CREATE TABLE APPROVAL_LEVEL (

	LEVEL_ID SERIAL NOT NULL, 
	CONFIG_ID INTEGER NOT NULL, 
	LEVEL_INDEX INTEGER NOT NULL, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (LEVEL_ID) 
);


CREATE TABLE APPROVAL_LEVEL_SUPERVISOR (

	LEVEL_SUPERVISOR_ID SERIAL NOT NULL, 
	LEVEL_ID INTEGER NOT NULL, 
	SUPERVISOR_ID INTEGER NOT NULL, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (LEVEL_SUPERVISOR_ID) 
);


CREATE TABLE APPROVAL_SUMMARY (

	APPROVAL_ID SERIAL NOT NULL, 
	ITEM_ID INTEGER NOT NULL, 
	LEVEL_ID INTEGER NOT NULL, 
	REQUESTOR INTEGER NOT NULL, 
	REQUEST_AT TIMESTAMP NOT NULL, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (APPROVAL_ID) 
);


CREATE TABLE APPROVAL_SUMMARY_HISTORY (

	HISTORY_ID SERIAL NOT NULL, 
	ACTION VARCHAR(32) NOT NULL, 
	COMMENT TEXT NOT NULL, 
	ITEM_ID INTEGER NOT NULL, 
	LEVEL_ID INTEGER NOT NULL, 
	REQUESTOR INTEGER NOT NULL, 
	REQUEST_AT TIMESTAMP NOT NULL, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (HISTORY_ID) 
);


CREATE TABLE BOOKMARK_DOC (

	BOOKMARK_ID SERIAL NOT NULL, 
	DESCRIPTION TEXT NULL, 
	DOCUMENT_ID INTEGER NOT NULL, 
	DOC_TYPE INTEGER NULL, 
	LABEL TEXT NULL, 
	LINK_STRING TEXT NULL, 
	OWNER_CORP_CODE VARCHAR(32) NOT NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (BOOKMARK_ID) 
);


CREATE TABLE BOOKMARK_VIDEO (

	BOOKMARK_ID SERIAL NOT NULL, 
	DESCRIPTION TEXT NULL, 
	DOCUMENT_ID INTEGER NOT NULL, 
	END_SEC DOUBLE PRECISION NULL, 
	LABEL TEXT NULL, 
	OWNER_CORP_CODE VARCHAR(32) NOT NULL, 
	START_SEC DOUBLE PRECISION NULL, 
	VIDEO_TYPE INTEGER NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (BOOKMARK_ID) 
);


CREATE TABLE BUDGET (

	BUDGET_ID SERIAL NOT NULL, 
	BUDGET DOUBLE PRECISION NULL, 
	END_DATE DATE NULL, 
	ORGANIZATION_CODE VARCHAR(32) NULL, 
	START_DATE DATE NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (BUDGET_ID) 
);


CREATE TABLE CHECKLIST (

	CKLIST_LOG_ID SERIAL NOT NULL, 
	ACTION_CODE VARCHAR(32) NULL, 
	CHECK_DATE DATE NULL, 
	CKLIST_LOG_CODE VARCHAR(32) NULL, 
	HOSP_PSN VARCHAR(32) NULL, 
	MEASURE_DEV1 VARCHAR(32) NULL, 
	MEASURE_DEV2 VARCHAR(32) NULL, 
	REFER_CKLIST_CODE VARCHAR(32) NOT NULL, 
	SERVICE_OFFICE VARCHAR(32) NULL, 
	SERVICE_PSN VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (CKLIST_LOG_ID) 
);


CREATE TABLE CHECKLIST_ITEM (

	CKI_LOG_ID SERIAL NOT NULL, 
	CKI_LOG_CODE VARCHAR(32) NULL, 
	CKLIST_LOG_CODE VARCHAR(32) NOT NULL, 
	IS_OK INTEGER NULL, 
	REFER_CKI_CODE VARCHAR(32) NOT NULL, 
	RESULT_DESCRIPTION TEXT NULL, 
	RESULT_VALUE TEXT NULL, 
	SERV_PSN VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (CKI_LOG_ID) 
);


CREATE TABLE CONTRACT (

	CONTRACT_ID SERIAL NOT NULL, 
	CONTRACT_CODE VARCHAR(32) NULL, 
	CONTRACT_DATE DATE NULL, 
	CONTRACT_TYPE VARCHAR(32) NULL, 
	DESCRIPTION TEXT NULL, 
	END_DATE DATE NULL, 
	FEE_DISCOUNT_PRICE DOUBLE PRECISION NULL, 
	FEE_DISCOUNT_RATE DOUBLE PRECISION NULL, 
	HOSP_CODE VARCHAR(32) NULL, 
	NAME VARCHAR(255) NULL, 
	PART_DISCOUNT_PRICE DOUBLE PRECISION NULL, 
	PART_DISCOUNT_RATE DOUBLE PRECISION NULL, 
	PRICE DOUBLE PRECISION NULL, 
	SERVICE_OFFICE VARCHAR(32) NULL, 
	SERVICE_PSN VARCHAR(32) NULL, 
	START_DATE DATE NULL, 
	TAX DOUBLE PRECISION NULL, 
	TOT_DISCOUNT_PRICE DOUBLE PRECISION NULL, 
	TOT_DISCOUNT_RATE DOUBLE PRECISION NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (CONTRACT_ID) 
);


CREATE TABLE CORPORATE (

	CORP_ID SERIAL NOT NULL, 
	CORP_CODE VARCHAR(32) NULL, 
	COUNTRY INTEGER NOT NULL, 
	NAME VARCHAR(255) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (CORP_ID) 
);


CREATE TABLE COUNT_RECORD (

	COUNT_RECORD_ID SERIAL NOT NULL, 
	CKLIST_CODE VARCHAR(32) NULL, 
	COUNT_BASE_CODE VARCHAR(32) NULL, 
	COUNT_REC_CODE VARCHAR(32) NULL, 
	DEV_CODE VARCHAR(32) NULL, 
	HOSP_DEPT_CODE VARCHAR(32) NULL, 
	RAW_VALUE DOUBLE PRECISION NULL, 
	RECORD_AT TIMESTAMP NULL, 
	UNIT VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (COUNT_RECORD_ID) 
);


CREATE TABLE COUNT_SCHEDULE_ITEM (

	COUNT_SCHED_ITEM_ID SERIAL NOT NULL, 
	ACTION_CODE VARCHAR(32) NULL, 
	ASSIGNED_PSN VARCHAR(32) NULL, 
	CKLIST_CODE VARCHAR(32) NULL, 
	COUNTER_BASE_CODE VARCHAR(32) NULL, 
	COUNT_SCHED_CODE VARCHAR(32) NULL, 
	DESCRIPTION TEXT NULL, 
	DISP_OFF_AT TIMESTAMP NULL, 
	DISP_OFF_BY VARCHAR(32) NULL, 
	END_DATE DATE NULL, 
	HOSP_DEPT_CODE VARCHAR(32) NULL, 
	IS_DISP_OFF INTEGER NULL, 
	SCHED_BASE_CODE VARCHAR(32) NULL, 
	SCHED_TITLE VARCHAR(255) NULL, 
	START_DATE DATE NULL, 
	TARGET_COUNT DOUBLE PRECISION NULL, 
	TARGET_DATE DATE NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (COUNT_SCHED_ITEM_ID) 
);


CREATE TABLE DEVICE (

	DEV_ID SERIAL NOT NULL, 
	ACCEPTANCE_DATE DATE NULL, 
	ACQ_CODE VARCHAR(32) NULL, 
	CLIENT_MGMT_CODE TEXT NULL, 
	DEV_CODE VARCHAR(32) NOT NULL, 
	EXPIRE_DATE DATE NULL, 
	HOSP_DEPT_CODE VARCHAR(32) NULL, 
	IMAGE_FILE BYTEA NULL, 
	INSTALL_DATE DATE NULL, 
	LAST_SERVICE_OFFICE VARCHAR(32) NULL, 
	LAST_SERVICE_PSN VARCHAR(32) NULL, 
	LOCATION TEXT NULL, 
	LOCATION_IMAGE BYTEA NULL, 
	MDEV_CODE VARCHAR(32) NULL, 
	NO_SERIAL_CONFIRM INTEGER NULL, 
	PRICE DOUBLE PRECISION NULL, 
	P_CCY INTEGER NULL, 
	SERIAL_NO VARCHAR(255) NULL, 
	SOFTWARE_REV VARCHAR(255) NULL, 
	SUPLLIER_OFFICE VARCHAR(32) NULL, 
	SUPPLIER_PSN VARCHAR(32) NULL, 
	TARGET_DEV_CODE VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (DEV_ID) 
);


CREATE TABLE DOCUMENT (

	DOC_ID SERIAL NOT NULL, 
	COUNTRY INTEGER NULL, 
	INST01 TEXT NULL, 
	INST_V TEXT NULL, 
	MDEV_CODE VARCHAR(32) NULL, 
	PERFORMANCE01 TEXT NULL, 
	PERFORMANCE_V TEXT NULL, 
	REPLACE_PART_V TEXT NULL, 
	SAFETY01 TEXT NULL, 
	SAFETY_V TEXT NULL, 
	SERVICE01 TEXT NULL, 
	SERVICE02 TEXT NULL, 
	SOFTWARE_REV VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (DOC_ID) 
);


CREATE TABLE FAULT (

	FAULT_ID SERIAL NOT NULL, 
	ACTION_CODE VARCHAR(32) NULL, 
	CAUSE TEXT NULL, 
	DESCRIPTION TEXT NULL, 
	IMAGE_FILE BYTEA NULL, 
	PREVENTION TEXT NULL, 
	REPAIR TEXT NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (FAULT_ID) 
);


CREATE TABLE HOSPITAL (

	HOSP_ID SERIAL NOT NULL, 
	CORP_CODE VARCHAR(32) NULL, 
	HOSP_CODE VARCHAR(32) NULL, 
	NAME VARCHAR(255) NULL, 
	NUM_BEDS INTEGER NULL, 
	OFFICE_CODE VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (HOSP_ID) 
);


CREATE TABLE HOSPITAL_DEPT (

	DEPT_ID SERIAL NOT NULL, 
	CHECK_DAYS_MARGIN INTEGER NULL, 
	DEPT_CODE VARCHAR(32) NULL, 
	HOSP_CODE VARCHAR(32) NULL, 
	NAME VARCHAR(255) NULL, 
	NOTICE_DAYS_BEFORE INTEGER NULL, 
	NUM_BEDS INTEGER NULL, 
	PICKUP_DAYS INTEGER NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (DEPT_ID) 
);


CREATE TABLE HUMAN_RESOURCE (

	HR_ID SERIAL NOT NULL, 
	CLASS_CODE VARCHAR(32) NULL, 
	HOSP_CODE VARCHAR(32) NULL, 
	HOSP_DEPT_CODE VARCHAR(32) NULL, 
	PSN_CODE VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (HR_ID) 
);


CREATE TABLE MDEV_CHECKLIST (

	CKLIST_ID SERIAL NOT NULL, 
	CKLIST_CODE VARCHAR(32) NULL, 
	MDEV_CODE VARCHAR(32) NULL, 
	NAME VARCHAR(255) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (CKLIST_ID) 
);


CREATE TABLE MDEV_CHECKLIST_ITEM (

	CKI_ID SERIAL NOT NULL, 
	CKI_CODE VARCHAR(32) NULL, 
	CKLIST_CODE VARCHAR(32) NULL, 
	COUNTRY INTEGER NULL, 
	DESCRIPTION TEXT NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (CKI_ID) 
);


CREATE TABLE MDEV_OPERATOR (

	MDEV_SERVICE_ID SERIAL NOT NULL, 
	MDEV_CODE VARCHAR(32) NULL, 
	ROLE_CODE VARCHAR(32) NULL, 
	SERVICE_OFFICE VARCHAR(32) NULL, 
	SERVICE_PSN VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (MDEV_SERVICE_ID) 
);


CREATE TABLE MDEV_PURCHASE (

	MDEV_PURCHASE_ID SERIAL NOT NULL, 
	DIST_OFFICE VARCHAR(32) NULL, 
	DIST_PSN VARCHAR(32) NULL, 
	LEAD_TIME TEXT NULL, 
	MDEV_CODE VARCHAR(32) NULL, 
	NOTICE TEXT NULL, 
	PAY_COND TEXT NULL, 
	PRICE DOUBLE PRECISION NULL, 
	PRICE_DATE DATE NULL, 
	PRICE_EVIDENCE_FILE BYTEA NULL, 
	P_CCY INTEGER NULL, 
	ROLE_CODE VARCHAR(32) NULL, 
	WHOLESALE_PRICE DOUBLE PRECISION NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (MDEV_PURCHASE_ID) 
);


CREATE TABLE MT_COUNTRY (

	COUNTRY_ID SERIAL NOT NULL, 
	NAME VARCHAR(255) NULL, 
	NAME_EN VARCHAR(255) NULL, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (COUNTRY_ID) 
);


CREATE TABLE MT_CURRENCY (

	CCY_ID SERIAL NOT NULL, 
	CCY_LOCAL_POST VARCHAR(255) NULL, 
	CCY_LOCAL_PRE VARCHAR(255) NULL, 
	CCY_NAME VARCHAR(3) NULL, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (CCY_ID) 
);


CREATE TABLE M_DEVICE (

	MDEV_ID SERIAL NOT NULL, 
	CATALOG TEXT NULL, 
	CAT_NAME VARCHAR(255) NULL, 
	COUNTRY INTEGER NULL, 
	MANUFACTURER_CODE VARCHAR(32) NULL, 
	MANUFACTURER_PSN VARCHAR(32) NULL, 
	MDEV_CODE VARCHAR(32) NULL, 
	MDEV_TYPE INTEGER NULL, 
	MODEL_NO VARCHAR(255) NULL, 
	NAME VARCHAR(255) NULL, 
	NOTICE TEXT NULL, 
	OWNER_CORP_CODE VARCHAR(32) NULL, 
	PICTURE BYTEA NULL, 
	SPECIFICATION TEXT NULL, 
	SUPPLIER_CODE VARCHAR(32) NULL, 
	SUPPLIER_PSN VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (MDEV_ID) 
);


CREATE TABLE NOTICE_LOG (

	NOTICE_ID SERIAL NOT NULL, 
	DELETED_AT TIMESTAMP NULL, 
	DELETED_BY INTEGER NULL, 
	DESCRIPTION TEXT NULL, 
	TARGET_DEVICE VARCHAR(32) NULL, 
	TARGET_OFFICE VARCHAR(32) NULL, 
	TARGET_SCHED_ITEM VARCHAR(32) NULL, 
	TITLE VARCHAR(255) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (NOTICE_ID) 
);


CREATE TABLE OFFICE (

	OFFICE_ID SERIAL NOT NULL, 
	ACCOUNTANT_PSN VARCHAR(32) NULL, 
	ADDR_CODE VARCHAR(32) NULL, 
	CORP_CODE VARCHAR(32) NULL, 
	EQUIPMENT_MGR_PSN VARCHAR(32) NULL, 
	FAX VARCHAR(255) NULL, 
	MANAGER_PSN VARCHAR(32) NULL, 
	NAME VARCHAR(255) NULL, 
	OFFICE_CODE VARCHAR(32) NULL, 
	TAX_CODE VARCHAR(255) NULL, 
	TECHNICIAN_PSN VARCHAR(32) NULL, 
	TEL VARCHAR(255) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (OFFICE_ID) 
);


CREATE TABLE OPERATION_LOG (

	OP_ID BIGSERIAL NOT NULL, 
	APPROVED_BY INTEGER NOT NULL, 
	DESCRIPTION TEXT NULL, 
	NEW_ID INTEGER NULL, 
	OLD_ID INTEGER NULL, 
	OPERATED_AT TIMESTAMP NULL, 
	OPERATED_BY INTEGER NOT NULL, 
	TARGET_TABLE VARCHAR(255) NULL, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (OP_ID) 
);


CREATE TABLE PARTS_LIST (

	PARTS_LIST_ID SERIAL NOT NULL, 
	MDEV_CODE VARCHAR(32) NULL, 
	PART_CODE VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (PARTS_LIST_ID) 
);


CREATE TABLE PART_ESTIMATE (

	PE_ID SERIAL NOT NULL, 
	ACTION_CODE VARCHAR(32) NULL, 
	CLIENT_SIDE_MGMT_CODE VARCHAR(32) NULL, 
	DIST_OFFICE VARCHAR(32) NULL, 
	DIST_PSN VARCHAR(32) NULL, 
	EXPIRE_DATE DATE NULL, 
	IMAGE_FILE BYTEA NULL, 
	NOTICE TEXT NULL, 
	PE_CODE VARCHAR(32) NOT NULL, 
	PE_TYPE VARCHAR(32) NULL, 
	PRINT_DATE DATE NULL, 
	P_CCY INTEGER NULL, 
	RECEIVE_DATE DATE NULL, 
	REQUESTER_OFFICE VARCHAR(32) NULL, 
	REQUESTER_PSN VARCHAR(32) NULL, 
	REQUEST_DATE DATE NULL, 
	REQ_DELIVERY_DATE DATE NULL, 
	REQ_DEST_OFFICE VARCHAR(32) NULL, 
	SERVICE_OFFICE VARCHAR(32) NULL, 
	SERVICE_PSN VARCHAR(32) NULL, 
	TAX DOUBLE PRECISION NULL, 
	TOTAL_PRICE DOUBLE PRECISION NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (PE_ID) 
);


CREATE TABLE PART_ESTIMATE_ITEM (

	PEI_ID INTEGER NOT NULL, 
	ITEM_PRICE DOUBLE PRECISION NULL, 
	NUM_ITEMS INTEGER NULL, 
	PART_CODE VARCHAR(32) NULL, 
	PART_MODEL_NO VARCHAR(255) NULL, 
	PART_NAME VARCHAR(255) NULL, 
	PE_CODE VARCHAR(32) NULL, 
	PRICE_WITH_TAX DOUBLE PRECISION NULL, 
	TAX DOUBLE PRECISION NULL, 
	TAX_RATE DOUBLE PRECISION NULL, 
	TOT_PRICE DOUBLE PRECISION NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (PEI_ID) 
);


CREATE TABLE PART_ORDER (

	PO_ID SERIAL NOT NULL, 
	ACTION_CODE VARCHAR(32) NULL, 
	DEST_OFFICE VARCHAR(32) NULL, 
	DIST_MGMT_CODE VARCHAR(32) NULL, 
	DIST_OFFICE VARCHAR(32) NULL, 
	DIST_PSN VARCHAR(32) NULL, 
	ESTIMATE_CODE VARCHAR(32) NULL, 
	ETA_DATE DATE NULL, 
	IMAGE_FILE BYTEA NULL, 
	ORDER_DATE DATE NULL, 
	PAYMENT_TERMS TEXT NULL, 
	PAY_DATE DATE NULL, 
	PO_CODE VARCHAR(32) NULL, 
	P_CCY INTEGER NULL, 
	REQUESTER_OFFICE VARCHAR(32) NULL, 
	REQUESTER_PSN VARCHAR(32) NULL, 
	SERVICE_OFFICE VARCHAR(32) NULL, 
	SERVICE_PSN VARCHAR(32) NULL, 
	STATUS INTEGER NULL, 
	TAX DOUBLE PRECISION NULL, 
	TOTAL_PRICE DOUBLE PRECISION NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (PO_ID) 
);


CREATE TABLE PART_ORDER_ITEM (

	POI_ID SERIAL NOT NULL, 
	ITEM_PRICE DOUBLE PRECISION NULL, 
	NUM_ITEMS INTEGER NULL, 
	PART_CODE VARCHAR(32) NULL, 
	PART_MODEL_NO VARCHAR(255) NULL, 
	PART_NAME VARCHAR(255) NULL, 
	PO_CODE VARCHAR(32) NULL, 
	PRICE_WITH_TAX DOUBLE PRECISION NULL, 
	TAX DOUBLE PRECISION NULL, 
	TAX_RATE DOUBLE PRECISION NULL, 
	TOT_PRICE DOUBLE PRECISION NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (POI_ID) 
);


CREATE TABLE PERSON (

	PSN_ID SERIAL NOT NULL, 
	ADDR_CODE VARCHAR(32) NULL, 
	CONTACT_METHOD TEXT NULL, 
	EMAIL VARCHAR(255) NULL, 
	FAX VARCHAR(255) NULL, 
	NAME VARCHAR(255) NULL, 
	OFFICE_CODE VARCHAR(32) NULL, 
	PSN_CODE VARCHAR(32) NULL, 
	TEL VARCHAR(255) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (PSN_ID) 
);


CREATE TABLE PERSON_CLASS (

	CLASS_ID SERIAL NOT NULL, 
	CLASS_CODE VARCHAR(32) NULL, 
	CLASS_LOCAL_POST VARCHAR(255) NULL, 
	CLASS_LOCAL_PRE VARCHAR(255) NULL, 
	COUNTRY_ID INTEGER NULL, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (CLASS_ID) 
);


CREATE TABLE PRESET_PHRASES (

	ID SERIAL NOT NULL, 
	CATEGORY_CODE VARCHAR(32) NULL, 
	COUNTRY INTEGER NULL, 
	INPUT_STR VARCHAR(255) NULL, 
	MEANING_CODE VARCHAR(32) NULL, 
	SHOW_STR VARCHAR(255) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (ID) 
);


CREATE TABLE REPAIRMAN (

	ID SERIAL NOT NULL, 
	ACTION_CODE VARCHAR(32) NULL, 
	SERVICE_OFFICE VARCHAR(32) NULL, 
	SERVICE_PSN VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (ID) 
);


CREATE TABLE REPL_PART (

	REPL_PART_ID SERIAL NOT NULL, 
	ACTION_CODE VARCHAR(32) NULL, 
	DELIVERY_METHOD TEXT NULL, 
	DEVICE_CODE VARCHAR(32) NULL, 
	IMAGE_FILE BYTEA NULL, 
	MEMO_REMOVED TEXT NULL, 
	REMOVED_DEV_CODE VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (REPL_PART_ID) 
);


CREATE TABLE ROLE_MASTER (

	ROLE_ID SERIAL NOT NULL, 
	COUNTRY INTEGER NULL, 
	LABEL VARCHAR(255) NULL, 
	ROLE_CODE VARCHAR(32) NULL, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (ROLE_ID) 
);


CREATE TABLE SCHEDULE (

	SCHED_BASE_ID SERIAL NOT NULL, 
	CKLIST_CODE VARCHAR(32) NULL, 
	DESCRIPTION TEXT NULL, 
	INTERVAL_MONTH INTEGER NULL, 
	MDEV_CODE VARCHAR(32) NULL, 
	NAME VARCHAR(255) NULL, 
	SCHED_BASE_CODE VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (SCHED_BASE_ID) 
);


CREATE TABLE SCHEDULE_ITEM (

	SCHED_ITEM_ID SERIAL NOT NULL, 
	ACTION_CODE VARCHAR(32) NULL, 
	ASSIGNED_PSN VARCHAR(32) NULL, 
	CKLIST_CODE VARCHAR(32) NULL, 
	DESCRIPTION TEXT NULL, 
	DEV_CODE VARCHAR(32) NULL, 
	DISP_OFF_AT TIMESTAMP NULL, 
	DISP_OFF_BY VARCHAR(32) NULL, 
	END_DATE DATE NULL, 
	HOSP_DEPT_CODE VARCHAR(32) NULL, 
	IS_DISP_OFF INTEGER NULL, 
	SCHED_BASE_CODE VARCHAR(32) NULL, 
	SCHED_CODE VARCHAR(32) NULL, 
	SCHED_TITLE VARCHAR(255) NULL, 
	START_DATE DATE NULL, 
	TARGET_DATE DATE NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (SCHED_ITEM_ID) 
);


CREATE TABLE SEARCH_CONDITION (

	SEARCH_COND_ID SERIAL NOT NULL, 
	CONDITION TEXT NULL, 
	COND_FORMAT_VER INTEGER NULL, 
	CREATOR_DISPLAY INTEGER NULL, 
	LABEL VARCHAR(255) NULL, 
	OFFICE_CODE VARCHAR(32) NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (SEARCH_COND_ID) 
);


CREATE TABLE USERS (

	USER_ID SERIAL NOT NULL, 
	ACCOUNT_TYPE INTEGER NULL, 
	EMAIL VARCHAR(255) NULL, 
	IS_SUPERVISOR INTEGER NULL, 
	LOGIN_NAME VARCHAR(255) NULL, 
	NAME TEXT NULL, 
	OFFICE_CODE VARCHAR(255) NULL, 
	PASSWORD VARCHAR(255) NULL, 
	PSN_CODE VARCHAR(32) NULL, 
	SALT VARCHAR(255) NULL, 
	SESSIONID VARCHAR(255) NULL, 
	THEME VARCHAR(32) NULL, 
	CHECKED_AT TIMESTAMP NULL, 
	CHECKED_BY INTEGER NULL, 
	IS_DELETED INTEGER NOT NULL DEFAULT 0, 
	CREATED_AT TIMESTAMP NULL, 
	CREATED_BY INTEGER NOT NULL DEFAULT 0, 
	OBJECT_VERSION INTEGER NOT NULL DEFAULT 0, 	

	PRIMARY KEY (USER_ID) 
);
